/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  env: [
    {type: 'autogenerated', dirName: '01-env'}
  ],
  html: [
    {type: 'autogenerated', dirName: '02-html'}
  ],
  wordpress: [
    {type: 'autogenerated', dirName: '03-wordpress'}
  ],
  fegg: [
    {type: 'autogenerated', dirName: '04-fegg'}
  ],

  // // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // // But you can create a sidebar manually
  // /*
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
  //  */
};
